import { createRequire } from 'node:module';
import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const require = createRequire(import.meta.url);
const sharp = require(process.env.SHARP_MODULE || 'sharp');
const root = fileURLToPath(new URL('../', import.meta.url));
const sprites = JSON.parse(await readFile(path.join(root, 'sources/sprites.json'), 'utf8'));
const size = 512;
const transparent = { r: 0, g: 0, b: 0, alpha: 0 };
const categories = ['ingredients', 'produce', 'staples', 'cookware', 'utensils', 'appliances'];
const seen = new Set();
for (const folder of ['assets/png', 'assets/webp', 'assets/sprite', 'dist', 'docs/previews', 'docs/social']) {
  await mkdir(path.join(root, folder), { recursive: true });
}
const catalog = [];
for (const sprite of sprites) {
  if (!/^[a-z][a-z0-9_]*$/.test(sprite.id) || seen.has(sprite.id)) throw new Error(`Invalid/duplicate ID: ${sprite.id}`);
  seen.add(sprite.id);
  const individual = typeof sprite.source === 'string';
  if (!categories.includes(sprite.category) || (individual
    ? sprite.source !== `sources/individual/${sprite.id}.png`
    : !Number.isInteger(sprite.cell) || sprite.cell < 0 || sprite.cell > 8)) {
    throw new Error(`Invalid sprite: ${sprite.id}`);
  }
  const source = individual ? path.join(root, sprite.source) : path.join(root, 'sources/atlases', `${sprite.atlas}.webp`);
  const meta = await sharp(source).metadata();
  if (!meta.hasAlpha || !meta.width || !meta.height) throw new Error(`Source must have alpha: ${sprite.id}`);
  const region = individual ? { x: 0, y: 0, width: 1, height: 1 }
    : { x: (sprite.cell % 3) / 3, y: Math.floor(sprite.cell / 3) / 3, width: 1 / 3, height: 1 / 3, ...sprite.crop };
  const left = Math.round(region.x * meta.width);
  const top = Math.round(region.y * meta.height);
  const width = Math.min(meta.width - left, Math.round(region.width * meta.width));
  const height = Math.min(meta.height - top, Math.round(region.height * meta.height));
  if (left < 0 || top < 0 || width <= 0 || height <= 0) throw new Error(`Invalid crop: ${sprite.id}`);
  const tile = await sharp(source).extract({ left, top, width, height }).png().toBuffer();
  const trimmed = await sharp(tile).trim({ threshold: 18 }).png().toBuffer();
  const canvas = await sharp(trimmed).resize(448, 448, { fit: 'contain', background: transparent })
    .extend({ top: 32, bottom: 32, left: 32, right: 32, background: transparent }).png().toBuffer();
  const png = `assets/png/${sprite.id}.png`;
  const webp = `assets/webp/${sprite.id}.webp`;
  await sharp(canvas).png({ compressionLevel: 9 }).toFile(path.join(root, png));
  await sharp(canvas).webp({ quality: 90, alphaQuality: 100 }).toFile(path.join(root, webp));
  catalog.push({ id: sprite.id, category: sprite.category, alt: { en: sprite.en, ro: sprite.ro }, width: size, height: size,
    png, webp, license: 'CC0-1.0' });
}
const json = JSON.stringify(catalog, null, 2);
await writeFile(path.join(root, 'catalog.json'), `${json}\n`);
await writeFile(path.join(root, 'docs/catalog.js'), `window.CulinaryCatalog = ${json};\n`);
const ids = catalog.map(asset => JSON.stringify(asset.id)).join(' | ');
const categoryTypes = categories.map(category => JSON.stringify(category)).join(' | ');
const commonTypes = `export type AssetId = ${ids};\nexport type Category = ${categoryTypes};\nexport interface AssetMetadata { readonly id: AssetId; readonly category: Category; readonly alt: Readonly<{ en: string; ro: string }>; readonly width: 512; readonly height: 512; readonly png: string; readonly webp: string; readonly license: 'CC0-1.0' }\nexport declare const catalog: readonly AssetMetadata[];\n`;
await writeFile(path.join(root, 'dist/index.d.ts'), `${commonTypes}export declare const assets: Readonly<Record<AssetId, AssetMetadata & { readonly src: string; readonly pngSrc: string }>>;\nexport declare function getAsset(id: AssetId): (typeof assets)[AssetId];\n`);
await writeFile(path.join(root, 'dist/native.d.ts'), `${commonTypes}export declare const nativeAssets: Readonly<Record<AssetId, number>>;\n`);
const webEntries = catalog.map(a => `  ${JSON.stringify(a.id)}: Object.freeze({ ...catalog[${catalog.indexOf(a)}], src: new URL('../${a.webp}', import.meta.url).href, pngSrc: new URL('../${a.png}', import.meta.url).href })`).join(',\n');
await writeFile(path.join(root, 'dist/index.js'), `// Generated by scripts/build.mjs; do not edit.\nexport const catalog = Object.freeze(${JSON.stringify(catalog)}.map(a => Object.freeze({ ...a, alt: Object.freeze(a.alt) })));\nexport const assets = Object.freeze({\n${webEntries}\n});\nexport function getAsset(id) { if (!Object.hasOwn(assets, id)) throw new RangeError('Unknown culinary asset: ' + id); return assets[id]; }\n`);
const nativeEntries = catalog.map(a => `  ${JSON.stringify(a.id)}: require('../${a.png}')`).join(',\n');
await writeFile(path.join(root, 'dist/native.cjs'), `// Generated static requires for Metro; do not edit.\nconst catalog = Object.freeze(require('../catalog.json').map(a => Object.freeze({ ...a, alt: Object.freeze(a.alt) })));\nconst nativeAssets = Object.freeze({\n${nativeEntries}\n});\nmodule.exports = { catalog, nativeAssets };\n`);
// Optional small-icon atlases avoid decoding a 130 x 512px sheet on mobile.
const columns = 13;
const tileSize = 128;
const rows = Math.ceil(catalog.length / columns);
const coordinates = Object.fromEntries(catalog.map((asset, index) => [asset.id, {
  x: (index % columns) * tileSize, y: Math.floor(index / columns) * tileSize,
  width: tileSize, height: tileSize,
}]));
for (const scale of [1, 2]) {
  const layers = [];
  for (const asset of catalog) {
    const position = coordinates[asset.id];
    layers.push({ input: await sharp(path.join(root, asset.png))
      .resize(tileSize * scale, tileSize * scale).png().toBuffer(),
    left: position.x * scale, top: position.y * scale });
  }
  await sharp({ create: { width: columns * tileSize * scale, height: rows * tileSize * scale,
    channels: 4, background: transparent } }).composite(layers)
    .webp({ quality: 90, alphaQuality: 100 })
    .toFile(path.join(root, `assets/sprite/culinary${scale === 2 ? '@2x' : ''}.webp`));
}
const atlas = { version: 1, tileSize, width: columns * tileSize, height: rows * tileSize,
  image: 'culinary.webp', image2x: 'culinary@2x.webp', scale2x: 2, sprites: coordinates };
await writeFile(path.join(root, 'assets/sprite/atlas.json'), `${JSON.stringify(atlas, null, 2)}\n`);
await writeFile(path.join(root, 'dist/sprite.js'), `// Generated optional web entry; does not import the main collection.\nexport const spriteUrl = new URL('../assets/sprite/culinary.webp', import.meta.url).href;\nexport const sprite2xUrl = new URL('../assets/sprite/culinary@2x.webp', import.meta.url).href;\nexport const spriteWidth = ${atlas.width};\nexport const spriteHeight = ${atlas.height};\nexport const tileSize = ${tileSize};\nexport const sprites = Object.freeze(Object.fromEntries(Object.entries(${JSON.stringify(coordinates)}).map(([id, position]) => [id, Object.freeze(position)])));\n`);
await writeFile(path.join(root, 'dist/sprite.d.ts'), `import type { AssetId } from './index.js';\nexport interface SpriteRect { readonly x: number; readonly y: number; readonly width: 128; readonly height: 128 }\nexport declare const spriteUrl: string;\nexport declare const sprite2xUrl: string;\nexport declare const spriteWidth: ${atlas.width};\nexport declare const spriteHeight: ${atlas.height};\nexport declare const tileSize: 128;\nexport declare const sprites: Readonly<Record<AssetId, SpriteRect>>;\n`);
for (const category of [...categories, 'collection']) {
  const items = category === 'collection' ? catalog : catalog.filter(a => a.category === category);
  const columns = category === 'collection' ? 11 : 3;
  const tileSize = category === 'collection' ? 144 : 240;
  const layers = [];
  for (const [index, asset] of items.entries()) {
    layers.push({ input: await sharp(path.join(root, asset.png)).resize(tileSize, tileSize).png().toBuffer(),
      left: (index % columns) * tileSize, top: Math.floor(index / columns) * tileSize });
  }
  const preview = await sharp({ create: { width: columns * tileSize, height: Math.ceil(items.length / columns) * tileSize,
    channels: 4, background: transparent } }).composite(layers).png().toBuffer();
  await sharp(preview).webp({ quality: 88, alphaQuality: 100 })
    .toFile(path.join(root, 'docs/previews', `${category}.webp`));
  if (category === 'collection') {
    await sharp(preview).flatten({ background: '#ffffff' }).png({ compressionLevel: 9 })
      .toFile(path.join(root, 'docs/social', `culinary-assets-${catalog.length}.png`));
  }
}
console.log(`Built ${catalog.length} assets, PNG + WebP, optional 1x/2x sprites, web + native exports, 7 preview sheets.`);
